#!/bin/bash
set -e

# Builds the plugin repository's index.yml, which is what Stash reads to list the available plugins.
# Outputs to the given directory (default: _site).
#
# Each plugin is described by a manifest at plugins/<plugin_id>.yml. These are generated by each plugin's own release
# process and contain the plugin's index entry, with path set to the absolute URL of the plugin's zip (hosted as an
# asset of the plugin's GitHub release, so GitHub tracks how many times each version is downloaded).

outdir="$1"
if [ -z "$outdir" ]; then
    outdir="_site"
fi

rm -rf "$outdir"
mkdir -p "$outdir"
touch "$outdir"/index.yml

addPlugin()
{
    f=$1

    echo "Adding $(basename "$f" .yml)"

    # turn the manifest into a list item, dropping comments and blank lines
    grep -v -e '^[[:space:]]*#' -e '^[[:space:]]*$' "$f" | sed -e 's/\r//' -e '1s/^/- /' -e '2,$s/^/  /' >> "$outdir"/index.yml
    echo "" >> "$outdir"/index.yml
}

find ./plugins -mindepth 1 -maxdepth 1 -name "*.yml" | sort | while read file; do
    addPlugin "$file"
done
