#!/bin/bash
set -e

# Adds (or updates) a plugin in the repository from a GitHub release of the plugin's own repo, by writing the
# plugins/<plugin_id>.yml manifest which build_site.sh turns into the plugin's index.yml entry. The plugin zip stays
# hosted as a release asset, so GitHub tracks how many times each version is downloaded.
#
# The release must have a zip asset containing the plugin's files, with the plugin's <plugin_id>.yml at the root.
# Requires the gh CLI to be installed and authenticated.
#
# Arguments:
#   $1 - The plugin's GitHub repo (e.g. secondfolder/stash-tv)
#   $2 - The release's tag (e.g. v2.27.0)
#   $3 - (optional) The name of the zip asset, only needed if the release has more than one

repo=$1
tag=$2
asset=$3

if [ -z "$repo" ] || [ -z "$tag" ]; then
    echo "Usage: $0 <owner/repo> <tag> [asset name]" >&2
    exit 1
fi

cd "$(dirname "$0")/.."

release=$(gh api "repos/$repo/releases/tags/$tag")

if [ -z "$asset" ]; then
    zips=$(echo "$release" | jq -r '.assets[] | select(.name | endswith(".zip")) | .name')
    if [ "$(echo "$zips" | grep -c .)" != "1" ]; then
        echo "Error: expected exactly one zip asset in $repo $tag but found: ${zips:-none}" >&2
        exit 1
    fi
    asset=$zips
fi

url=$(echo "$release" | jq -r --arg name "$asset" '.assets[] | select(.name == $name) | .browser_download_url')
if [ -z "$url" ]; then
    echo "Error: no asset named $asset in $repo $tag" >&2
    exit 1
fi

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

echo "Downloading $url"
gh release download "$tag" --repo "$repo" --pattern "$asset" --dir "$tmpdir"
zipfile="$tmpdir/$asset"

# the plugin's id is the name of its yml file
ymls=$(unzip -Z1 "$zipfile" | grep -E '^[^/]+\.yml$' || true)
if [ "$(echo "$ymls" | grep -c .)" != "1" ]; then
    echo "Error: expected exactly one yml file at the root of $asset but found: ${ymls:-none}" >&2
    exit 1
fi
plugin_id=$(basename "$ymls" .yml)
unzip -p "$zipfile" "$ymls" > "$tmpdir/plugin.yml"

# Get the value of a top level field from the plugin's yml file
getField() {
    grep "^$1:" "$tmpdir/plugin.yml" | head -n 1 | cut -d' ' -f2- | sed -e 's/\r//'
}

name=$(getField name)
description=$(getField description)
version=$(getField version | sed -e 's/^"\(.*\)"$/\1/')
if [ -z "$version" ]; then
    version=${tag#v}
fi
dep=$(grep "^# requires:" "$tmpdir/plugin.yml" | cut -c 12- | sed -e 's/\r//' || true)
date=$(echo "$release" | jq -r '.published_at // .created_at' | sed -e 's/T/ /' -e 's/Z$//')
sha256=$(sha256sum "$zipfile" | cut -d' ' -f1)

manifest="plugins/$plugin_id.yml"
echo "Writing $manifest for $plugin_id $version"
mkdir -p plugins
cat > "$manifest" << EOF
# Generated by scripts/publish-plugin.sh from $repo's $tag release. Do not edit manually.
id: $plugin_id
name: $name
metadata:
  description: $description
version: $version
date: $date
path: $url
sha256: $sha256
EOF

if [ -n "$dep" ]; then
    echo "requires:" >> "$manifest"
    for d in ${dep//,/ }; do
        echo "  - $d" >> "$manifest"
    done
fi

# Let the GitHub workflow know what was published
if [ -n "$GITHUB_OUTPUT" ]; then
    echo "plugin_id=$plugin_id" >> "$GITHUB_OUTPUT"
    echo "version=$version" >> "$GITHUB_OUTPUT"
fi
